import { router, useLocalSearchParams } from 'expo-router';
import { createElement } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';

const mapDocument = `<!doctype html><html><head><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;margin:0}</style></head><body><div id="map"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script><script>const a=[-33.4318,-70.6096],b=[-33.4257,-70.6152];const m=L.map('map').setView(a,15);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(m);L.polyline([b,[-33.4278,-70.6128],[-33.4292,-70.6115],a],{color:'#0B7C78',weight:6}).addTo(m);L.marker(a).addTo(m).bindPopup('Tu domicilio');L.marker(b).addTo(m).bindPopup('Técnico en camino');</script></body></html>`;

export default function WebServiceDetail() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const title = id === 'electricidad' ? 'Electricidad' : id === 'cerrajeria' ? 'Cerrajería' : 'Plomería';
  return <ThemedView style={styles.screen}><SafeAreaView style={styles.safe}><View style={styles.map}>{createElement('iframe', { title: 'Mapa OpenStreetMap', srcDoc: mapDocument, style: styles.iframe })}<Pressable onPress={() => router.back()} style={styles.back}><ThemedText style={styles.backText}>‹</ThemedText></Pressable><View style={styles.label}><ThemedText style={styles.title}>Técnico en camino</ThemedText><ThemedText themeColor="textSecondary" style={styles.sub}>Mapa real · OpenStreetMap</ThemedText></View></View><View style={styles.sheet}><ThemedText style={styles.status}>En camino · Llega en 12 min</ThemedText><ThemedText themeColor="textSecondary" style={styles.address}>Av. Providencia 1420, Depto 402, Santiago</ThemedText><View style={styles.divider} /><ThemedText style={styles.person}>Roberto Méndez · Maestro certificado</ThemedText><ThemedText themeColor="textSecondary" style={styles.service}>{title} · Desde $18.000</ThemedText><Pressable onPress={() => router.back()} style={styles.button}><ThemedText style={styles.buttonText}>Volver al catálogo</ThemedText></Pressable></View></SafeAreaView></ThemedView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F8FC' }, safe: { flex: 1 }, map: { flex: 1 }, iframe: { borderWidth: 0, width: '100%', height: '100%' }, back: { position: 'absolute', top: 14, left: 16, width: 40, height: 40, borderRadius: 13, backgroundColor: '#FFF', alignItems: 'center', justifyContent: 'center' }, backText: { fontSize: 28, color: '#303449' }, label: { position: 'absolute', top: 14, left: 68, right: 16, backgroundColor: '#FFF', borderRadius: 13, padding: 9 }, title: { color: '#34384D', fontSize: 12, fontWeight: '800' }, sub: { fontSize: 9, marginTop: 2 }, sheet: { backgroundColor: '#FFF', borderTopLeftRadius: 25, borderTopRightRadius: 25, padding: 20 }, status: { color: '#292E43', fontSize: 14, fontWeight: '800' }, address: { fontSize: 11, marginTop: 10 }, divider: { height: 1, backgroundColor: '#EFF0F4', marginVertical: 14 }, person: { color: '#2C3044', fontSize: 13, fontWeight: '800' }, service: { fontSize: 11, marginTop: 5 }, button: { minHeight: 46, borderRadius: 12, backgroundColor: '#0B7C78', alignItems: 'center', justifyContent: 'center', marginTop: 18 }, buttonText: { color: '#FFF', fontSize: 12, fontWeight: '800' }, });
