import { Pressable, ScrollView, StyleSheet, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { ThemedText } from '@/components/themed-text';
import { ThemedView } from '@/components/themed-view';
import { useSession } from '@/context/session';

export default function ProfileScreen() {
  const { session } = useSession();
  return <ThemedView style={styles.screen}><SafeAreaView edges={['top']} style={styles.safe}><ScrollView contentContainerStyle={styles.content}><ThemedText themeColor="textSecondary" style={styles.eyebrow}>MANOCERCA / CUENTA</ThemedText><ThemedText style={styles.title}>Mi perfil</ThemedText><View style={styles.profileCard}><View style={styles.avatar}><ThemedText style={styles.avatarText}>{session?.name?.[0] ?? 'M'}</ThemedText></View><View><ThemedText style={styles.name}>{session?.name ?? 'Usuario ManoCerca'}</ThemedText><ThemedText themeColor="textSecondary" style={styles.email}>{session?.email}</ThemedText><View style={styles.badge}><ThemedText style={styles.badgeText}>{session?.role === 'tecnico' ? 'Técnico verificado' : 'Cliente protegido'}</ThemedText></View></View></View><View style={styles.guarantee}><ThemedText style={styles.guaranteeIcon}>✓</ThemedText><View><ThemedText style={styles.guaranteeTitle}>Protección ManoCerca</ThemedText><ThemedText themeColor="textSecondary" style={styles.guaranteeText}>Servicios verificados y soporte durante tu solicitud.</ThemedText></View></View>{['Datos personales', 'Direcciones guardadas', 'Métodos de pago', 'Ayuda y soporte'].map((item) => <Pressable key={item} style={styles.option}><ThemedText style={styles.optionText}>{item}</ThemedText><ThemedText style={styles.arrow}>›</ThemedText></Pressable>)}</ScrollView></SafeAreaView></ThemedView>;
}

const styles = StyleSheet.create({ screen: { flex: 1, backgroundColor: '#F7F8FC' }, safe: { flex: 1 }, content: { padding: 20, paddingBottom: 130 }, eyebrow: { fontSize: 10, letterSpacing: 1.4, fontWeight: '800', marginTop: 8 }, title: { fontSize: 28, fontWeight: '800', color: '#272940', marginTop: 7, marginBottom: 20 }, profileCard: { backgroundColor: '#FFF', borderRadius: 18, padding: 18, flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#E8EBF2' }, avatar: { width: 58, height: 58, borderRadius: 19, backgroundColor: '#DDF1EF', alignItems: 'center', justifyContent: 'center', marginRight: 14 }, avatarText: { color: '#0B7C78', fontSize: 22, fontWeight: '800' }, name: { color: '#2C3044', fontSize: 17, fontWeight: '800' }, email: { fontSize: 11, marginTop: 3 }, badge: { alignSelf: 'flex-start', backgroundColor: '#EAF7F5', borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4, marginTop: 7 }, badgeText: { color: '#0B7C78', fontSize: 9, fontWeight: '800' }, guarantee: { backgroundColor: '#EAF0FF', borderRadius: 16, padding: 15, flexDirection: 'row', alignItems: 'center', marginTop: 16, marginBottom: 16 }, guaranteeIcon: { width: 30, height: 30, borderRadius: 15, backgroundColor: '#5962D5', color: '#FFF', textAlign: 'center', lineHeight: 30, fontWeight: '800', marginRight: 10 }, guaranteeTitle: { color: '#30356B', fontWeight: '800', fontSize: 12 }, guaranteeText: { fontSize: 10, marginTop: 3 }, option: { backgroundColor: '#FFF', minHeight: 52, borderRadius: 13, borderWidth: 1, borderColor: '#E8EBF2', paddingHorizontal: 15, alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 9 }, optionText: { color: '#34384D', fontSize: 12, fontWeight: '700' }, arrow: { color: '#0B7C78', fontSize: 23 }, });
